name: dropofhope
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0+2
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  google_places_flutter: ^2.1.0  # Changed to stable version
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png